[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --log-format defmt"

[env]
DEFMT_LOG = "info"
SSID = "Wifi: star-vision box_2.4G"
PASSWORD = "Starvision@2025"
#  SSID = "MyCanalBox-2G"
#  PASSWORD = "aDrQZYTp3A"
#  SSID = "Gandema"
#  PASSWORD = "main1234"


[build]
rustflags = ["-C", "link-arg=-nostartfiles"]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
